services:
  - type: web
    name: class-board-project
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    disk:
      name: uploads-share
      mountPath: /opt/render/project/src/static/uploads
      sizeGB: 1